---
title: "Differential expression per cluster analysis"
author: "Evert Bosdriesz"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
    code_folding: hide
editor_options:
  markdown:
    wrap: sentence
bibliography: references.bib
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(tidymodels)
library(here)

source(here("src", "graphics-options.R"))

## Global options
options(max.print = "80")
opts_chunk$set(
  echo = TRUE, cache = FALSE, prompt = FALSE, tidy = FALSE, comment = NA,
  message = FALSE, warning = FALSE
)
opts_knit$set(width = 80)
```

Our input data looks as follows:

```{r load_data}
dat_tmm <- read_tsv(here("data", "processed", "scIDseq-vanEijl-tmm.tsv")) %>% 
  select(sample_id, treatment, ab_name, ab_type, ab_count_tmm) %>% 
  filter(treatment != "No_EGF") %>% 
  mutate(treatment = factor(treatment, levels = c("EGF", "ip70S6K_EGF", "iRSK_EGF")))


head(dat_tmm)
```
```{r}
dat <- dat_tmm %>% 
  select(-ab_type) %>% 
  pivot_wider(names_from = ab_name, values_from = ab_count_tmm)
```

```{r}

tmp <- mpmi::cmi(select(dat, -sample_id, -treatment))

tmp$
```

